version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:651783354148:task-definition/aws-hello-world-rest-api-2:2"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-rest-api-2"
          ContainerPort: 80
        PlatformVersion: "LATEST"